manifest:
  version: 0.7

  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.5.0
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-ncs.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - mbedtls-nrf
          - mcuboot
          - net-tools
          - nrfxlib
          - tfm-mcuboot
          - trusted-firmware-m
          - qcbor
          - segger
          - tinycrypt

    - name: golioth-zephyr-boards
      path: app/golioth-boards
      revision: 807f33254c1747e5d6ab13051efbc5c19f893551
      url: git@github.com:golioth/golioth-zephyr-boards.git
  self:
    path: app
