# Copyright (c) 2022-2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: 0.8

  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.8.0
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-ncs.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - mbedtls-nrf
          - mcuboot
          - net-tools
          - nrfxlib
          - qcbor
          - segger
          - tfm-mcuboot
          - tinycrypt
          - trusted-firmware-m
          - zcbor

    - name: golioth-zephyr-boards
      path: deps/modules/lib/golioth-boards
      revision: v1.0.1
      url: https://github.com/golioth/golioth-zephyr-boards

    - name: libostentus
      path: deps/modules/lib/libostentus
      revision: 0bd726006b9f43c6578224f2ea7607800c2377d0
      url: https://github.com/golioth/libostentus

  self:
    path: app
