# Copyright (c) 2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test firmware    

on:
  pull_request:

  push:

jobs:
  test_build:
    runs-on: ubuntu-latest

    env:
        ZEPHYR_SDK: 0.16.3
        BOARD: aludel_mini_v1_sparkfun9160_ns

    steps:
      -  uses: ./.github/workflows/build_zephyr.yml
         with:
           ZEPHYR_SDK: ${{ github.env.ZEPHYR_SDK }}
           BOARD: ${{ github.env.BOARD }}